// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuyllwikoyawwymeygcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1eWxsd2lrb3lhd3d5bWV5Z2NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwOTcxODIsImV4cCI6MjA3MjY3MzE4Mn0.C1k74nxMqVn39j_tWuLUXpYShoWs5yJxC5bNwsKebh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});